#!/usr/bin/env bash

# Exit immediately if:
# - Any command fails
# - Any part of a pipeline fails
# - We reference any unbound variables
set -euo pipefail

# If environment variable DEBUG is set to 1, run in debug mode.
if [ "${DEBUG:-}" = 1 ]
then
  echo "Running in debug mode. Set DEBUG to 0 to disable."
  set -x
fi

VARS="huss
pr
ps
rsds
sfcWind
tas
tasmax
tasmin"

VARS="pr
ps
rsds
sfcWind
tas
tasmax
tasmin"

BARRA2=/scratch/hw83/dh7190/barra2

SCRIPT_DIR="${BARRA2}/scripts"
LOG_DIR="${BARRA2}/logs"
OUT_DIR="${BARRA2}/reshaped"

mkdir -p "${SCRIPT_DIR}" "${LOG_DIR}" "${OUT_DIR}"

CMD=/home/590/dh7190/code/lpj-guess/scripts/ozflux-lpjg/ncreshape

# Arguments which will be common to all invocations of pbs_wrap.
RESOURCES="-c 1 -m 8 -q normal -w 48:00:00 -M python3/3.12.1"
EMAIL="d.holzworth@westernsydney.edu.au"

PBS_ARGS="${RESOURCES} -e ${EMAIL} -l ${LOG_DIR}"

for VAR in ${VARS}
do
	echo "Generating ${VAR} script..."
    JOB_NAME="reshape_${VAR}"
    SCRIPT="${SCRIPT_DIR}/${JOB_NAME}"

	# Dependent job ID.
	if [ "${VAR}" = sfcWind ]
	then
		DEP="113619296.gadi-pbs"
	elif [ "${VAR}" = tasmax ]
	then
		DEP="113619298.gadi-pbs"
	elif [ "${VAR}" = tasmin ]
	then
		DEP="113619299.gadi-pbs"
	else
		DEP="$(qstat | /usr/bin/grep "mergetime_${VAR}" | cut -d' ' -f1)"
	fi

    PROGRESS_FILE="${LOG_DIR}/${JOB_NAME}.progress.log"

	FILE_NAME="${VAR}_AUS-11_ERA5_historical_hres_BOM_BARRA-R2_v1_1hr_197901-202308.nc"
    IN_FILE="${BARRA2}/mergetime/${FILE_NAME}"
    OUT_FILE="${OUT_DIR}/${FILE_NAME}"

    # todo: verify handling of variable names containing whitespace.
    CMD_ARGS="-pv3 -i ${IN_FILE} -o ${OUT_FILE} --chunk-size lat/1,lon/1,time/17520 --compression-level 5 --dimension-order lat,lon,time --min-chunk-size 128 | tee ${PROGRESS_FILE}"
    pbs_wrap ${PBS_ARGS} -n ${JOB_NAME} -o ${SCRIPT} -d "${DEP}" "${CMD}" ${CMD_ARGS}
    # qsub "${SCRIPT}"
done
