#!/usr/bin/env bash
set -euo pipefail

TIMESTEP=day

BASE_DIR=/scratch/pt17/dh7190/barra2/trunk

IN_DIR="${BASE_DIR}/test"
OUT_DIR="${BASE_DIR}/remapped"
SCRIPT_DIR="${BASE_DIR}/scripts"
LOG_DIR="${BASE_DIR}/logs"

mkdir -p "${OUT_DIR}" "${SCRIPT_DIR}" "${LOG_DIR}"


# Air temperature in K
# Precipitation in kg m-2 s-1
# Shortwave radiation in W m-2
# Min/max air temperature in K (optional, only required for blaze)
# Wind speed in m s-1 (optional, required only for blaze)
#
# Air pressure in Pa (optional, can use rel. humidity instead)
# Specific humidity, unitless (optional, can use rel. humidity instead)
# Relative humidity, unitless (optional, can use spe. humidity instead)
#
# Requires (air pressure and specific humidity) OR (relative humidity)

VARS="huss tas pr rsds tasmax tasmin ps hurs sfcWind"
GRID=/home/590/dh7190/code/lpj-guess/scripts/input_processing/barra2/barra2.grid

for VAR in ${VARS}
do
    IN_FILE="${IN_DIR}/${VAR}_AUS-11_ERA5_historical_hres_BOM_BARRA-R2_v1_${TIMESTEP}_197901-202312.nc"
    OUT_FILE="${OUT_DIR}/$(basename "${IN_FILE}")"

    JOB_NAME="remap_${VAR}"
    SCRIPT_FILE="${SCRIPT_DIR}/${JOB_NAME}"
    cat >"${SCRIPT_FILE}" <<EOF
#!/usr/bin/env bash
#PBS -l ncpus=1
#PBS -l walltime=24:00:00
#PBS -l mem=4GB
#PBS -q normal
#PBS -l wd
#PBS -j oe
#PBS -m abe
#PBS -M d.holzworth@westernsydney.edu.au
#PBS -l storage=scratch/pt17
#PBS -N ${JOB_NAME}
#PBS -o ${LOG_DIR}/${JOB_NAME}.log

set -euo pipefail

IN_FILE="${IN_FILE}"
OUT_FILE="${OUT_FILE}"
GRID="${GRID}"

cdo -O remapcon,"\${GRID}" "\${IN_FILE}" "\${OUT_FILE}"
echo "Successfully remapped ${VAR}!"

EOF

    chmod u+x "${SCRIPT_FILE}"
    # qsub "${SCRIPT_FILE}"
done
