#!/usr/bin/env bash
#PBS -l ncpus=192
#PBS -l walltime=04:00:00
#PBS -l mem=3072GB
#PBS -q hugemem
#PBS -l wd
#PBS -j oe
#PBS -m abe
#PBS -M d.holzworth@westernsydney.edu.au
#PBS -l storage=scratch/pt17
#PBS -N bom_regrid
#PBS -o /home/590/dh7190/code/lpj-guess/scripts/input_processing/bom-lai/logs

set -euo pipefail

module purge
module load openmpi netcdf nco cdo python3/3.12.1

mpirun -np 192 /home/590/dh7190/code/lpj-guess/scripts/input_processing/bom-lai/bom_regrid_wrapper

