#!/usr/bin/env bash
set -euo pipefail

TIMESTEP=day
IN_DIR="/g/data/ob53/BARRA2/output/reanalysis/AUS-11/BOM/ERA5/historical/hres/BARRA-R2/v1/${TIMESTEP}"

BARRA2_OUT=/scratch/pt17/dh7190/barra2/trunk

OUT_DIR="${BARRA2_OUT}/test"
SCRIPT_DIR="${BARRA2_OUT}/scripts"
LOG_DIR="${BARRA2_OUT}/logs"

mkdir -p "${OUT_DIR}" "${SCRIPT_DIR}" "${LOG_DIR}"


# Air temperature in K
# Precipitation in kg m-2 s-1
# Shortwave radiation in W m-2
# Min/max air temperature in K (optional, only required for blaze)
# Wind speed in m s-1 (optional, required only for blaze)
#
# Air pressure in Pa (optional, can use rel. humidity instead)
# Specific humidity, unitless (optional, can use rel. humidity instead)
# Relative humidity, unitless (optional, can use spe. humidity instead)
#
# Requires (air pressure and specific humidity) OR (relative humidity)

VARS="huss tas pr rsds tasmax tasmin ps hurs sfcWind"

for VAR in ${VARS}
do
    VAR_IN_DIR="${IN_DIR}/${VAR}/latest"
    OUT_FILE="${OUT_DIR}/${VAR}_AUS-11_ERA5_historical_hres_BOM_BARRA-R2_v1_${TIMESTEP}_197901-202312.nc"

    JOB_NAME="mergetime_${VAR}"
    SCRIPT_FILE="${SCRIPT_DIR}/${JOB_NAME}"
    cat >"${SCRIPT_FILE}" <<EOF
#!/usr/bin/env bash
#PBS -l ncpus=1
#PBS -l walltime=04:00:00
#PBS -l mem=4GB
#PBS -q normal
#PBS -l wd
#PBS -j oe
#PBS -m abe
#PBS -M d.holzworth@westernsydney.edu.au
#PBS -l storage=scratch/pt17+gdata/ob53
#PBS -N ${JOB_NAME}
#PBS -o ${LOG_DIR}/${JOB_NAME}.log

set -euo pipefail

IN_DIR="${VAR_IN_DIR}"
OUT_FILE="${OUT_FILE}"

cdo -O mergetime --unpack "\${IN_DIR}"/*.nc "\${OUT_FILE}"
echo "Successfully merged ${VAR} files!"

EOF

    chmod u+x "${SCRIPT_FILE}"
    qsub "${SCRIPT_FILE}"
done
