#!/usr/bin/env bash
set -euo pipefail

TIMESTEP=day

BASE_DIR=/scratch/pt17/dh7190/barra2/trunk

IN_DIR="${BASE_DIR}/remapped"
OUT_DIR="${BASE_DIR}/optimised"
SCRIPT_DIR="${BASE_DIR}/scripts"
LOG_DIR="${BASE_DIR}/logs"

mkdir -p "${OUT_DIR}" "${SCRIPT_DIR}" "${LOG_DIR}"

VARS="huss tas pr rsds tasmax tasmin ps hurs sfcWind"
VARS=sfcWind

for VAR in ${VARS}
do
    IN_FILE="${IN_DIR}/${VAR}_AUS-11_ERA5_historical_hres_BOM_BARRA-R2_v1_${TIMESTEP}_197901-202312.nc"
    OUT_FILE="${OUT_DIR}/$(basename "${IN_FILE}")"

    JOB_NAME="optim_${VAR}"
    SCRIPT_FILE="${SCRIPT_DIR}/${JOB_NAME}"
    cat >"${SCRIPT_FILE}" <<EOF
#!/usr/bin/env bash
#PBS -l ncpus=1
#PBS -l walltime=24:00:00
#PBS -l mem=16GB
#PBS -q normal
#PBS -l wd
#PBS -j oe
#PBS -m abe
#PBS -M d.holzworth@westernsydney.edu.au
#PBS -l storage=scratch/pt17
#PBS -N ${JOB_NAME}
#PBS -o ${LOG_DIR}/${JOB_NAME}.log

set -euo pipefail

IN_FILE="${IN_FILE}"
OUT_FILE="${OUT_FILE}"

# Fix dimension order and chunk sizes, and enable netcdf compression (zlib L5).
ncpdq -O -L5 -a latitude,longitude,time --cnk_dmn latitude,1 --cnk_dmn longitude,1 --cnk_dmn time,365 "\${IN_FILE}" "\${OUT_FILE}"

# Change units of latitude/longitude. lpj-guess is picky about capitalisation.
ncatted -O -a units,longitude,o,c,degrees_east "${OUT_FILE}"
ncatted -O -a units,latitude,o,c,degrees_north "${OUT_FILE}"

echo "Successfully optimised ${VAR}!"

EOF

    chmod u+x "${SCRIPT_FILE}"
    # qsub "${SCRIPT_FILE}"
done
