#!/usr/bin/env bash

# Exit immediately if:
# - Any command fails
# - Any part of a pipeline fails
# - We reference any unbound variables
set -euo pipefail

# If environment variable DEBUG is set to 1, run in debug mode.
if [ "${DEBUG:-}" = 1 ]
then
    echo "Running in debug mode. Set DEBUG to 0 to disable."
    set -x
fi

# Get directory containing this script.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd -P)"

source "${DIR}/barpa_config"
source "${DIR}/barpa_helpers"

MODELS="ACCESS-CM2 ACCESS-ESM1-5 CESM2 CMCC-ESM2 EC-Earth3 ERA5 MPI-ESM1-2-HR NorESM2-MM"
MODELS="ACCESS-ESM1-5"

SCENARIOS="historical ssp126 ssp370"
SCENARIOS=historical
SCENARIOS="ssp126"

for MODEL in ${MODELS}
do
    for SCENARIO in ${SCENARIOS}
    do
        DRIVING_EXPERIMENT_ID="${SCENARIO}"
        "${DIR}/barpa_processing"
    done
done
