#!/usr/bin/env bash
set -euo pipefail

dotnet test --collect:"XPlat Code Coverage"

# dotnet tool install -g dotnet-reportgenerator-globaltool
test -d coveragereport && rm -rf coveragereport
reportgenerator -reports:"**/coverage.cobertura.xml" -targetdir:"coveragereport" -reporttypes:Html

xdg-open coveragereport/index.html
