#!/usr/bin/env bash
#PBS -N download_crujra
#PBS -P pt17
#PBS -q copyq
#PBS -l walltime=10:00:00
#PBS -l mem=4GB
#PBS -l ncpus=1
#PBS -l storage=scratch/pt17
#PBS -l wd
#PBS -j oe
#PBS -m abe
#PBS -M d.holzworth@westernsydney.edu.au

# Fail immediately if any command fails.
set -euo pipefail

# Version of the dataset to be downloaded.
VERSION="2.2"

# Source directory.
SRC="simba:/data/cru_jra/${VERSION}"

# Destination directory.
DST="/scratch/pt17/dh7190/forcing/cru_jra"

# Create the output directory if it doesn't already exist.
mkdir -p "${DST}"

# Get current directory.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd -P)"
LOG_FILE="${DIR}/download_crujra_${VERSION}.progress.log"

# Download the data.
rsync -a --partial --info=progress2 --no-i-r "${SRC}" "${DST}/" | tee "${LOG_FILE}"
